#
TARGET = hps-c

# CC = arm-linux-gnueabilhf-gcc -g -Wall main.c -o hps-c

#
CROSS_COMPILE = arm-linux-gnueabilhf-
CFLAGS = -g -Wall -I ${SOCEDS_DEST_ROOT}/ip/altera_hps/hwlib/include
LDFLAGS = -g -Wall
CC = ${CROSS_COMPILE}gcc
ARCH = arm

build: $(TARGET)

$(TARGET): main.o
	$(CC) $(LDFLAGS) $^ -o $@

%.o : %.c
	$(CC) $(CFLAGS) -c $< -o $@

.PHONY: clean
clean:
	rm -f $(TARGET) *.a *.o *~
