#
CC = arm-linux-gnueabihf-g++
SOURCE = ga-main.cpp
TARGET = ga-program
HEADER = ga-main.h cellgen.h
CFLAGS = -g -Wall -std=c++11
INCLUDE = -I../hwlib/include/ -I../hwlib/include/soc_cv_av/ -I../ref/

# Cross Compile for ARM
arm :
	$(CC) $(CFLAGS) $(INCLUDE) $(SOURCE) -o $(TARGET)

# Complile for PC
pc :
	g++ $(CFLAGS) $(INCLUDE) $(SOURCE) -o $(TARGET).exe

clean :
	rm -f $(TARGET) *.a *.o *.exe
